[project]
name = "gen-and-agnentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.14",
    "langchain-cohere>=0.6.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.3",
    "langchain-openai>=1.4.1",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "pydantic>=2.13.4",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "arxiv>=2.1.0",
    "fastembed>=0.8.0",
    "feedparser>=6.0.14",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "langchain-arxiv>=0.1.0",
    "rich>=15.0.0",
]
